---
# file: site.yml

- name: Install and configure basic software and user accounts
  hosts: 127.0.0.1
  connection: local
  remote_user: root
  gather_facts: yes

  roles:
    - common
    - users
    - ntp
