---
# file: roles/users/vars/main.yml
# Defines a list of users in the system

# groups can be comma separated list
# add user to wheel group for sudo access
users:
  - name: Nick Hentschel
    username: nhentschel
    shell: /bin/bash
    primary_group: users
    add_to_groups: "wheel"
    state: present
    keys:
      - nhentschel.pub
  - name: Neel Shah
    username: nshah
    shell: /bin/bash
    primary_group: users
    add_to_groups: "wheel"
    state: present
    keys:
      - nshah.pub
  - name: Tushar Swamy
    username: tswamy
    shell: /bin/bash
    primary_group: users
    add_to_groups: "wheel"
    state: present
    keys:
      - tswamy.pub
  - name: Nick Materise
    username: nmaterise
    shell: /bin/bash
    primary_group: users
    add_to_groups: "wheel"
    state: present
    keys:
      - nmaterise.pub
  - name: Nathan VanBenschoten
    username: nvanbenschoten
    shell: /bin/bash
    primary_group: users
    add_to_groups: "wheel"
    state: present
    keys:
      - nvanbenschoten.pub
